# Generated by Django 6.0.1 on 2026-01-22 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='MyUser',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
