# Generated by Django 6.0.1 on 2026-01-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_backend', '0004_alter_myuser_options_alter_myuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
    ]
