# Generated by Django 6.0.1 on 2026-01-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_backend', '0008_directchat_groupchat_message_userprofile_groupmember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
