# Generated by Django 6.0.1 on 2026-01-23 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_backend', '0009_myuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='email',
        ),
    ]
