# Generated by Django 6.0.1 on 2026-01-24 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_backend', '0011_myuser_age_myuser_gender'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagereceipt',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='messagereceipt',
            name='message',
        ),
        migrations.RemoveField(
            model_name='messagereceipt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='directchat',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='groupchat',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='groupchat',
            name='description',
        ),
        migrations.RemoveField(
            model_name='groupchat',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_edited',
        ),
        migrations.RemoveField(
            model_name='message',
            name='media',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_type',
        ),
        migrations.RemoveField(
            model_name='message',
            name='reply_to',
        ),
        migrations.RemoveField(
            model_name='message',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='gender',
        ),
        migrations.AlterField(
            model_name='directchat',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats1', to='chat_backend.myuser'),
        ),
        migrations.AlterField(
            model_name='directchat',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats2', to='chat_backend.myuser'),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_backend.myuser'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(max_length=256),
        ),
        migrations.DeleteModel(
            name='GroupMember',
        ),
        migrations.DeleteModel(
            name='MessageReceipt',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
